apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: subha92/vprofileapp:latest
          ports:
            - name: vproapp-port
              containerPort: 8080
      initContainers:
        - name: init_mydb
          image: busybox
          command: ['sh', '-c', 'untill nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
        - name: init_memcache
          image: busybox
          command: [ 'sh', '-c', 'untill nslookup vprocache01; do echo waiting for vpromc; sleep 2; done;' ]